name: CI

on:
  push:
  pull_request:

jobs:
  test_c:
    name: "${{matrix.cstd}}/${{matrix.cc}}/${{matrix.os}}"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        cc:
          - gcc
          - clang
        cstd:
          - c89
          - c99
          - c11
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: make -C test lang_c CC=${{matrix.cc}} CFLAGS="-std=${{matrix.cstd}}"
  test_cpp:
    name: "${{matrix.cxxstd}}/${{matrix.cxx}}/${{matrix.os}}"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        cxx:
          - g++
          - clang++
        cxxstd:
          - c++11
          - c++14
          - c++17
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: make -C test lang_cpp CXX=${{matrix.cxx}} CXXFLAGS="-std=${{matrix.cxxstd}}"
